spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:commercelab}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=${MYSQL_SERVER_TIMEZONE:Asia/Seoul}&characterEncoding=UTF-8
    username: ${MYSQL_USER:commercelab}
    password: ${MYSQL_PASSWORD:commercelab}
    driver-class-name: ${MYSQL_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
